# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-19 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0002_auto_20180917_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
