# Generated by Django 2.1.1 on 2018-09-02 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.CharField(max_length=10)),
                ('banco_responsavel', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(default=0.0)),
                ('numero_parcelas', models.IntegerField(default=0)),
                ('juros', models.FloatField(default=0.0)),
                ('nome_do_cartao', models.CharField(max_length=50)),
                ('vencimento_do_cartao', models.CharField(max_length=5)),
                ('cvv', models.IntegerField(default=0)),
                ('credito_ou_debito', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('endereco', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('valor', models.FloatField(default=0.0)),
                ('status_pagamento', models.BooleanField(default=False)),
                ('boleto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Boleto')),
                ('cartao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Cartao')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Cliente')),
            ],
        ),
    ]
