# Generated by Django 2.1.1 on 2018-09-03 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField()),
                ('banco', models.CharField(max_length=50)),
                ('numero_boleto', models.CharField(default='0', max_length=50)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandeira_cartao', models.CharField(max_length=30)),
                ('num_parcelas', models.IntegerField()),
                ('num_cartao', models.CharField(max_length=20)),
                ('juros', models.FloatField()),
                ('nome_cartao', models.CharField(max_length=50)),
                ('data_vencimento_cartao', models.DateField()),
                ('CVV', models.IntegerField()),
                ('credito', models.BooleanField()),
                ('debito', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('CPF', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('telefone', models.CharField(max_length=20)),
                ('RG', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boleto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pagamento.Boleto')),
                ('cartao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pagamento.Cartao')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pagamento.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('infos_produto', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='pagamento',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pagamento.Pedido'),
        ),
    ]
