# Generated by Django 2.1.1 on 2018-09-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='infos_produto',
            field=models.TextField(max_length=200),
        ),
    ]
