# Generated by Django 2.1.1 on 2018-09-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='bandeira_cartao',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
