# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-03 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0003_boleto_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='boleto',
            old_name='data_vencimento',
            new_name='data_vencimento_boleto',
        ),
        migrations.RenameField(
            model_name='boleto',
            old_name='status',
            new_name='status_boleto',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='data_emissao',
            new_name='data_emissao_pedido',
        ),
    ]
