# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-20 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ownerGroup', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('type_produto', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('quantityInStock', models.IntegerField(default=0)),
                ('value', models.FloatField(default=0.0)),
                ('availableToSell', models.BooleanField(default=False)),
                ('weight', models.FloatField(default=0.0)),
                ('imageURLs', models.CharField(max_length=100000)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
