# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-20 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20181020_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='id_produto',
            field=models.CharField(default='-1', max_length=100),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
