# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-20 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20181020_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=15)),
                ('sessionToken', models.CharField(max_length=300)),
            ],
        ),
    ]
