# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20181021_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrinho',
            old_name='total',
            new_name='total_carrinho',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='id_logistica',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='id_pagamento',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='total_frete',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produtos_no_carrinho',
            name='valor_unitario',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='produtos_no_carrinho',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
