# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-30 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20181025_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acesso_API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('API', models.CharField(max_length=100)),
                ('id_API', models.CharField(max_length=500)),
                ('data_acesso', models.DateField()),
            ],
        ),
    ]
