# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-31 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_usuario_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='acesso_api',
            name='descricao',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
