# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-31 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_acesso_api_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acesso_api',
            name='descricao',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
