# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-31 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20181031_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acesso_api',
            name='id_API',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
