# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-02 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_remove_acesso_api_id_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='complemento',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='numero_residencia',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
