# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-02 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20181102_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='cep',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
