# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-05 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_carrinho_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='id_logistica',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
