# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-05 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20181105_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='id_logistica',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
