# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-07 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20181105_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='tempo_entrega',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
